### ISSUE TITLE
Model link is not available

### ISSUE THREAD

**Issue by frank-chan-ck** [Daikenan/LTMU#16]
Thank you for your work. The link of https://drive.google.com/open?id=1o-btxlWWA6GlbwMGCGkzn2vAw9qv8D2z  is not available yet. Are there any alternative links？

**Comment by Daikenan** [comment]
Baidu Yun link:https://pan.baidu.com/s/1LTQ_lmEP55uQOaARP6pLEw 
extract code: yyci

**Comment by frank-chan-ck** [comment]
> Baidu Yun link:https://pan.baidu.com/s/1LTQ_lmEP55uQOaARP6pLEw
> extract code: yyci

Thanks
