### ISSUE TITLE
'tuple' object has no attribute 'keys'

### ISSUE THREAD

**Issue by sunhao12121** [Daikenan/LTMU#3]
thanks for your great job. When I run `python run_tracker.py dimp dimp50` under the folder `DiMP_LTMU/pytracking`

I got a mistake:   'tuple' object has no attribute 'keys'

it seems that the the result of 
[`def track` function   in  `tracker/dimp/dimp.py` ](https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/pytracking/tracker/dimp/dimp.py#L154)  does not match the code in 
[`tracker/base/basetracker.py`](https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/pytracking/tracker/base/basetracker.py#L71)

Maybe I used the wrong settings.

**Comment by sunhao12121** [comment]
change the code here:
[https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/pytracking/tracker/dimp/dimp.py#L154](https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/pytracking/tracker/dimp/dimp.py#L154)
from `return new_state.tolist(), score_map.cpu().data.numpy()`
to `return {'target_bbox': new_state.tolist()}`
code seems running well, everything is fine.

**Comment by sunhao12121** [comment]
I ran wrong place. it seems that the code entrance is here:
[https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/run_tracker.py#L176](https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/run_tracker.py#L176)

the code I ran is the original dimp.

the `LTMU/DiMP_LTMU/Dimp_LTMU.py ` use the DIMP as default option:
[https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/Dimp_LTMU.py#L357](https://github.com/Daikenan/LTMU/blob/3bb2bcd061ab4f538e53a6c821e51e412970c2c1/DiMP_LTMU/Dimp_LTMU.py#L357)

**Comment by Daikenan** [comment]
Sorry for this inconvience, the testing and training tutorials are not yet complete, I will complete this part as soon as possible（within a few hours ）.
