### ISSUE TITLE
_prroi_pooling compile issue

### ISSUE THREAD

**Issue by BruthYU** [Daikenan/LTMU#6]
`Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
1.5.1
Loading extension module _prroi_pooling...
Traceback (most recent call last):
  File "./ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/yu/.conda/envs/LTMU/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/home/yu/.conda/envs/LTMU/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/yu/.conda/envs/LTMU/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1084, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/yu/.conda/envs/LTMU/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_prroi_pooling'`

Great work! 
Could you please tell me which version of Ninja should be used ?

**Comment by nihuo76** [comment]
Same problem here. Ninja is required.

**Comment by Daikenan** [comment]
`ImportError: No module named '_prroi_pooling'`: prroi_pooling did not compile successfully. You can compile it manually.

```
source activate DiMP_MU
cd LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool
bash travis.sh
```
after compile, the `_prroi_pooling` folder will be created in `LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool`.

Sometimes Ninja is also required, you can install it with any version mannully.

**Comment by BruthYU** [comment]
Thanks a lot for your guidance.
I found the origin repo of Precise RoI Pooling, but here is what confuses me:
In the requirement.txt, the version of torch is required to be 1.4.0. When I try to compile this with travis.sh, it raises an error:
```
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```
Then I change the env to
```
cuda_9.0 torch_0.4.0
```
The compilation is finished successfully，but after I change the env back to 
```
cuda_10.0 torch_1.4.0
``` 
Same error is raised in another python file.

**Comment by nihuo76** [comment]
> `ImportError: No module named '_prroi_pooling'`: prroi_pooling did not compile successfully. You can compile it manually.
> 
> ```
> source activate DiMP_MU
> cd LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool
> bash travis.sh
> ```
> 
> after compile, the `_prroi_pooling` folder will be created in `LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool`.
> 
> Sometimes Ninja is also required, you can install it with any version mannully.

Thanks, problem solved.

**Comment by BruthYU** [comment]
> > `ImportError: No module named '_prroi_pooling'`: prroi_pooling did not compile successfully. You can compile it manually.
> > ```
> > source activate DiMP_MU
> > cd LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool
> > bash travis.sh
> > ```
> > 
> > 
> > after compile, the `_prroi_pooling` folder will be created in `LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool`.
> > Sometimes Ninja is also required, you can install it with any version mannully.
> 
> Thanks, problem solved.

Which verison of torch you are using? I'm really confused about the error
```
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

**Comment by sallyzhixing** [comment]
请问一下，这三行，在哪里运行？
source activate DiMP_MU
cd LTMU/DiMP_MU/ltr/external/PreciseRoIPooling/pytorch/prroi_pool
bash travis.sh
